
classes:
- system.linux.system.single
#- system.openssh.server.team.lab
#- system.openssh.server.team.tcpcloud
#- system.openssh.server.team.mcp_qa
- cluster.test._team
- cluster.mcp.openstack
- cluster.mcp.opencontrail
- cluster.mcp.stacklight
- cluster.mcp.stacklight.client
- cluster.mcp.cicd
parameters:
  _param:
    salt_control_trusty_image: http://apt-mk.mirantis.com/images/ubuntu-14-04-x64-mcp1.0.qcow2
    salt_control_xenial_image: http://apt-mk.mirantis.com/images/ubuntu-16-04-x64-mcp1.0.qcow2

    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 172.17.36.90
    infra_config_deploy_address: 172.17.32.2

    cluster_domain: mcp.local
    cluster_name: mcp
    cluster_public_host: ${_param:openstack_proxy_address}
    infra_kvm_address: 172.17.36.126
    infra_kvm_node01_address: 172.17.36.123
    infra_kvm_node02_address: 172.17.36.124
    infra_kvm_node03_address: 172.17.36.125
    infra_kvm_node01_deploy_address: 172.17.32.101
    infra_kvm_node02_deploy_address: 172.17.32.83
    infra_kvm_node03_deploy_address: 172.17.32.102
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}

    control_network_netmask: 255.255.255.128
    tenant_network_netmask: 255.255.255.0
    control_vlan: 1361
    tenant_vlan: 1365

    dns_server01: 172.18.80.136
    dns_server02: 8.8.8.8
    deploy_network_netmask: 255.255.255.128
    deploy_network_gateway: 172.17.32.1

    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}
    tenant_network_gateway: 172.17.33.1

  salt:
    minion:
      trusted_ca_minions:
        - cfg

  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
